export const i18nData = [
  {
    name: 'Bahamas',
    nameOfficial: 'The Commonwealth of The Bahamas',
    alpha2: 'BS',
    alpha3: 'BHS',
    countryCode: '044',
    currencyName: 'Bahamian Dollar',
    currencyCode: 'BSD',
    currencyNumber: '044',
    countryCodeIso: 'ISO 3166-2:BS',
    ccTLD: '.bs',
    phoneCode: '+1242',
  },
  {
    name: 'Albania',
    nameOfficial: 'The Republic of Albania',
    alpha2: 'AL',
    alpha3: 'ALB',
    countryCode: '008',
    currencyName: 'Lek',
    currencyCode: 'ALL',
    currencyNumber: '008',
    countryCodeIso: 'ISO 3166-2:AL',
    ccTLD: '.al',
    phoneCode: '+355',
  },
  {
    name: 'Myanmar ',
    nameOfficial: 'The Republic of the Union of Myanmar',
    alpha2: 'MM',
    alpha3: 'MMR',
    countryCode: '104',
    currencyName: 'Kyat',
    currencyCode: 'MMK',
    currencyNumber: '104',
    countryCodeIso: 'ISO 3166-2:MM',
    ccTLD: '.mm',
    phoneCode: '+95',
  },
  {
    name: 'Burundi',
    nameOfficial: 'The Republic of Burundi',
    alpha2: 'BI',
    alpha3: 'BDI',
    countryCode: '108',
    currencyName: 'Burundi Franc',
    currencyCode: 'BIF',
    currencyNumber: '108',
    countryCodeIso: 'ISO 3166-2:BI',
    ccTLD: '.bi',
    phoneCode: '+257',
  },
  {
    name: 'Cambodia',
    nameOfficial: 'The Kingdom of Cambodia',
    alpha2: 'KH',
    alpha3: 'KHM',
    countryCode: '116',
    currencyName: 'Riel',
    currencyCode: 'KHR',
    currencyNumber: '116',
    countryCodeIso: 'ISO 3166-2:KH',
    ccTLD: '.kh',
    phoneCode: '+855',
  },
  {
    name: 'Algeria',
    nameOfficial: "The People's Democratic Republic of Algeria",
    alpha2: 'DZ',
    alpha3: 'DZA',
    countryCode: '012',
    currencyName: 'Algerian Dinar',
    currencyCode: 'DZD',
    currencyNumber: '012',
    countryCodeIso: 'ISO 3166-2:DZ',
    ccTLD: '.dz',
    phoneCode: '+213',
  },
  {
    name: 'Canada',
    nameOfficial: 'Canada',
    alpha2: 'CA',
    alpha3: 'CAN',
    countryCode: '124',
    currencyName: 'Canadian Dollar',
    currencyCode: 'CAD',
    currencyNumber: '124',
    countryCodeIso: 'ISO 3166-2:CA',
    ccTLD: '.ca',
    phoneCode: '+1',
  },
  {
    name: 'Cabo Verde ',
    nameOfficial: 'The Republic of Cabo Verde',
    alpha2: 'CV',
    alpha3: 'CPV',
    countryCode: '132',
    currencyName: 'Cabo Verde Escudo',
    currencyCode: 'CVE',
    currencyNumber: '132',
    countryCodeIso: 'ISO 3166-2:CV',
    ccTLD: '.cv',
    phoneCode: '+238',
  },
  {
    name: 'Cayman Islands',
    nameOfficial: 'The Cayman Islands',
    alpha2: 'KY',
    alpha3: 'CYM',
    countryCode: '136',
    currencyName: 'Cayman Islands Dollar',
    currencyCode: 'KYD',
    currencyNumber: '136',
    countryCodeIso: 'ISO 3166-2:KY',
    ccTLD: '.ky',
    phoneCode: '+1345',
  },
  {
    name: 'Sri Lanka',
    nameOfficial: 'The Democratic Socialist Republic of Sri Lanka',
    alpha2: 'LK',
    alpha3: 'LKA',
    countryCode: '144',
    currencyName: 'Sri Lanka Rupee',
    currencyCode: 'LKR',
    currencyNumber: '144',
    countryCodeIso: 'ISO 3166-2:LK',
    ccTLD: '.lk',
    phoneCode: '+94',
  },
  {
    name: 'Chile',
    nameOfficial: 'The Republic of Chile',
    alpha2: 'CL',
    alpha3: 'CHL',
    countryCode: '152',
    currencyName: 'Chilean Peso',
    currencyCode: 'CLP',
    currencyNumber: '152',
    countryCodeIso: 'ISO 3166-2:CL',
    ccTLD: '.cl',
    phoneCode: '+56',
  },
  {
    name: 'China',
    nameOfficial: "The People's Republic of China",
    alpha2: 'CN',
    alpha3: 'CHN',
    countryCode: '156',
    currencyName: 'Yuan Renminbi',
    currencyCode: 'CNY',
    currencyNumber: '156',
    countryCodeIso: 'ISO 3166-2:CN',
    ccTLD: '.cn',
    phoneCode: '+86',
  },
  {
    name: 'Colombia',
    nameOfficial: 'The Republic of Colombia',
    alpha2: 'CO',
    alpha3: 'COL',
    countryCode: '170',
    currencyName: 'Colombian Peso',
    currencyCode: 'COP',
    currencyNumber: '170',
    countryCodeIso: 'ISO 3166-2:CO',
    ccTLD: '.co',
    phoneCode: '+57',
  },
  {
    name: 'Comoros',
    nameOfficial: 'The Union of the Comoros',
    alpha2: 'KM',
    alpha3: 'COM',
    countryCode: '174',
    currencyName: 'Comoro Franc',
    currencyCode: 'KMF',
    currencyNumber: '174',
    countryCodeIso: 'ISO 3166-2:KM',
    ccTLD: '.km',
    phoneCode: '+269',
  },
  {
    name: 'Costa Rica',
    nameOfficial: 'The Republic of Costa Rica',
    alpha2: 'CR',
    alpha3: 'CRI',
    countryCode: '188',
    currencyName: 'Costa Rican Colon',
    currencyCode: 'CRC',
    currencyNumber: '191',
    countryCodeIso: 'ISO 3166-2:CR',
    ccTLD: '.cr',
    phoneCode: '+506',
  },
  {
    name: 'Croatia',
    nameOfficial: 'The Republic of Croatia',
    alpha2: 'HR',
    alpha3: 'HRV',
    countryCode: '191',
    currencyName: 'Kuna',
    currencyCode: 'HRK',
    currencyNumber: '192',
    countryCodeIso: 'ISO 3166-2:HR',
    ccTLD: '.hr',
    phoneCode: '+385',
  },
  {
    name: 'Cyprus',
    nameOfficial: 'The Republic of Cyprus',
    alpha2: 'CY',
    alpha3: 'CYP',
    countryCode: '196',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '203',
    countryCodeIso: 'ISO 3166-2:CY',
    ccTLD: '.cy',
    phoneCode: '+357',
  },
  {
    name: 'Benin',
    nameOfficial: 'The Republic of Benin',
    alpha2: 'BJ',
    alpha3: 'BEN',
    countryCode: '204',
    currencyName: 'CFA Franc BCEAO',
    currencyCode: 'XOF',
    currencyNumber: '208',
    countryCodeIso: 'ISO 3166-2:BJ',
    ccTLD: '.bj',
    phoneCode: '+229',
  },
  {
    name: 'Greece',
    nameOfficial: 'The Hellenic Republic',
    alpha2: 'GR',
    alpha3: 'GRC',
    countryCode: '300',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '208',
    countryCodeIso: 'ISO 3166-2:GR',
    ccTLD: '.gr',
    phoneCode: '+30',
  },
  {
    name: 'Estonia',
    nameOfficial: 'The Republic of Estonia',
    alpha2: 'EE',
    alpha3: 'EST',
    countryCode: '233',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '208',
    countryCodeIso: 'ISO 3166-2:EE',
    ccTLD: '.ee',
    phoneCode: '+372',
  },
  {
    name: 'Dominica',
    nameOfficial: 'The Commonwealth of Dominica',
    alpha2: 'DM',
    alpha3: 'DMA',
    countryCode: '212',
    currencyName: 'East Caribbean Dollar',
    currencyCode: 'XCD',
    currencyNumber: '214',
    countryCodeIso: 'ISO 3166-2:DM',
    ccTLD: '.dm',
    phoneCode: '+1767',
  },
  {
    name: 'Ecuador',
    nameOfficial: 'The Republic of Ecuador',
    alpha2: 'EC',
    alpha3: 'ECU',
    countryCode: '218',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '222',
    countryCodeIso: 'ISO 3166-2:EC',
    ccTLD: '.ec',
    phoneCode: '+593',
  },
  {
    name: 'Equatorial Guinea',
    nameOfficial: 'The Republic of Equatorial Guinea',
    alpha2: 'GQ',
    alpha3: 'GNQ',
    countryCode: '226',
    currencyName: 'CFA Franc BEAC',
    currencyCode: 'XAF',
    currencyNumber: '230',
    countryCodeIso: 'ISO 3166-2:GQ',
    ccTLD: '.gq',
    phoneCode: '+240',
  },
  {
    name: 'Ethiopia',
    nameOfficial: 'The Federal Democratic Republic of Ethiopia',
    alpha2: 'ET',
    alpha3: 'ETH',
    countryCode: '231',
    currencyName: 'Ethiopian Birr',
    currencyCode: 'ETB',
    currencyNumber: '232',
    countryCodeIso: 'ISO 3166-2:ET',
    ccTLD: '.et',
    phoneCode: '+251',
  },
  {
    name: 'Faroe Islands',
    nameOfficial: 'The Faroe Islands',
    alpha2: 'FO',
    alpha3: 'FRO',
    countryCode: '234',
    currencyName: 'Faroese króna',
    currencyCode: 'FOK',
    currencyNumber: '238',
    countryCodeIso: 'ISO 3166-2:FO',
    ccTLD: '.fo',
    phoneCode: '+298',
  },
  {
    name: 'Falkland Islands [Malvinas]',
    nameOfficial: 'The Falkland Islands',
    alpha2: 'FK',
    alpha3: 'FLK',
    countryCode: '238',
    currencyName: 'Falkland Islands Pound',
    currencyCode: 'FKP',
    currencyNumber: '238',
    countryCodeIso: 'ISO 3166-2:FK',
    ccTLD: '.fk',
    phoneCode: '+500',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    nameOfficial: 'South Georgia and the South Sandwich Islands',
    alpha2: 'GS',
    alpha3: 'SGS',
    countryCode: '239',
    currencyName: 'Falkland Islands pound',
    currencyCode: 'FKP',
    currencyNumber: '242',
    countryCodeIso: 'ISO 3166-2:GS',
    ccTLD: '.gs',
    phoneCode: '+500',
  },
  {
    name: 'French Polynesia',
    nameOfficial: 'French Polynesia',
    alpha2: 'PF',
    alpha3: 'PYF',
    countryCode: '258',
    currencyName: 'CFP Franc',
    currencyCode: 'XPF',
    currencyNumber: '262',
    countryCodeIso: 'ISO 3166-2:PF',
    ccTLD: '.pf',
    phoneCode: '+689',
  },
  {
    name: 'Georgia',
    nameOfficial: 'Georgia',
    alpha2: 'GE',
    alpha3: 'GEO',
    countryCode: '268',
    currencyName: 'Lari',
    currencyCode: 'GEL',
    currencyNumber: '270',
    countryCodeIso: 'ISO 3166-2:GE',
    ccTLD: '.ge',
    phoneCode: '+995',
  },
  {
    name: 'Ghana',
    nameOfficial: 'The Republic of Ghana',
    alpha2: 'GH',
    alpha3: 'GHA',
    countryCode: '288',
    currencyName: 'Ghana Cedi',
    currencyCode: 'GHS',
    currencyNumber: '292',
    countryCodeIso: 'ISO 3166-2:GH',
    ccTLD: '.gh',
    phoneCode: '+233',
  },
  {
    name: 'Argentina',
    nameOfficial: 'The Argentine Republic',
    alpha2: 'AR',
    alpha3: 'ARG',
    countryCode: '032',
    currencyName: 'Argentine Peso',
    currencyCode: 'ARS',
    currencyNumber: '032',
    countryCodeIso: 'ISO 3166-2:AR',
    ccTLD: '.ar',
    phoneCode: '+54',
  },
  {
    name: 'Guam',
    nameOfficial: 'The Territory of Guam',
    alpha2: 'GU',
    alpha3: 'GUM',
    countryCode: '316',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '320',
    countryCodeIso: 'ISO 3166-2:GU',
    ccTLD: '.gu',
    phoneCode: '+1671',
  },
  {
    name: 'Guatemala',
    nameOfficial: 'The Republic of Guatemala',
    alpha2: 'GT',
    alpha3: 'GTM',
    countryCode: '320',
    currencyName: 'Quetzal',
    currencyCode: 'GTQ',
    currencyNumber: '324',
    countryCodeIso: 'ISO 3166-2:GT',
    ccTLD: '.gt',
    phoneCode: '+502',
  },
  {
    name: 'Guinea',
    nameOfficial: 'The Republic of Guinea',
    alpha2: 'GN',
    alpha3: 'GIN',
    countryCode: '324',
    currencyName: 'Guinea Franc',
    currencyCode: 'GNF',
    currencyNumber: '328',
    countryCodeIso: 'ISO 3166-2:GN',
    ccTLD: '.gn',
    phoneCode: '+224',
  },
  {
    name: 'Guyana',
    nameOfficial: 'The Co-operative Republic of Guyana',
    alpha2: 'GY',
    alpha3: 'GUY',
    countryCode: '328',
    currencyName: 'Guyana Dollar',
    currencyCode: 'GYD',
    currencyNumber: '332',
    countryCodeIso: 'ISO 3166-2:GY',
    ccTLD: '.gy',
    phoneCode: '+592',
  },
  {
    name: 'Heard Island and McDonald Islands',
    nameOfficial: 'The Territory of Heard Island and McDonald Islands',
    alpha2: 'HM',
    alpha3: 'HMD',
    countryCode: '334',
    currencyName: 'Australian Dollar',
    currencyCode: 'AUD',
    currencyNumber: '340',
    countryCodeIso: 'ISO 3166-2:HM',
    ccTLD: '.hm',
    phoneCode: '+6723',
  },
  {
    name: 'Honduras',
    nameOfficial: 'The Republic of Honduras',
    alpha2: 'HN',
    alpha3: 'HND',
    countryCode: '340',
    currencyName: 'Lempira',
    currencyCode: 'HNL',
    currencyNumber: '344',
    countryCodeIso: 'ISO 3166-2:HN',
    ccTLD: '.hn',
    phoneCode: '+504',
  },
  {
    name: 'Hungary',
    nameOfficial: 'Hungary',
    alpha2: 'HU',
    alpha3: 'HUN',
    countryCode: '348',
    currencyName: 'Indian Rupee',
    currencyCode: 'INR',
    currencyNumber: '352',
    countryCodeIso: 'ISO 3166-2:HU',
    ccTLD: '.hu',
    phoneCode: '+36',
  },
  {
    name: 'Iceland',
    nameOfficial: 'Iceland',
    alpha2: 'IS',
    alpha3: 'ISL',
    countryCode: '352',
    currencyName: 'Iceland Krona',
    currencyCode: 'ISK',
    currencyNumber: '356',
    countryCodeIso: 'ISO 3166-2:IS',
    ccTLD: '.is',
    phoneCode: '+354',
  },
  {
    name: 'Hong Kong',
    nameOfficial: 'The Hong Kong Special Administrative Region of China',
    alpha2: 'HK',
    alpha3: 'HKG',
    countryCode: '344',
    currencyName: 'Hong Kong Dollar',
    currencyCode: 'HKD',
    currencyNumber: '356',
    countryCodeIso: 'ISO 3166-2:HK',
    ccTLD: '.hk',
    phoneCode: '+852',
  },
  {
    name: 'Namibia',
    nameOfficial: 'The Republic of Namibia',
    alpha2: 'NA',
    alpha3: 'NAM',
    countryCode: '516',
    currencyName: 'Namibia Dollar',
    currencyCode: 'NAD',
    currencyNumber: '036',
    countryCodeIso: 'ISO 3166-2:NA',
    ccTLD: '.na',
    phoneCode: '+264',
  },
  {
    name: 'Gibraltar',
    nameOfficial: 'Gibraltar',
    alpha2: 'GI',
    alpha3: 'GIB',
    countryCode: '292',
    currencyName: 'Gibraltar Pound',
    currencyCode: 'GIP',
    currencyNumber: '036',
    countryCodeIso: 'ISO 3166-2:GI',
    ccTLD: '.gi',
    phoneCode: '+350',
  },
  {
    name: 'Haiti',
    nameOfficial: 'The Republic of Haiti',
    alpha2: 'HT',
    alpha3: 'HTI',
    countryCode: '332',
    currencyName: 'Gourde',
    currencyCode: 'HTG',
    currencyNumber: '036',
    countryCodeIso: 'ISO 3166-2:HT',
    ccTLD: '.ht',
    phoneCode: '+509',
  },
  {
    name: 'Australia ',
    nameOfficial: 'The Commonwealth of Australia',
    alpha2: 'AU',
    alpha3: 'AUS',
    countryCode: '036',
    currencyName: 'Australian Dollar',
    currencyCode: 'AUD',
    currencyNumber: '036',
    countryCodeIso: 'ISO 3166-2:AU',
    ccTLD: '.au',
    phoneCode: '+61',
  },
  {
    name: 'Cocos (Keeling) Islands',
    nameOfficial: 'The Territory of Cocos (Keeling) Islands',
    alpha2: 'CC',
    alpha3: 'CCK',
    countryCode: '166',
    currencyName: 'Australian Dollar',
    currencyCode: 'AUD',
    currencyNumber: '036',
    countryCodeIso: 'ISO 3166-2:CC',
    ccTLD: '.cc',
    phoneCode: '+6189162',
  },
  {
    name: 'Christmas Island',
    nameOfficial: 'The Territory of Christmas Island',
    alpha2: 'CX',
    alpha3: 'CXR',
    countryCode: '162',
    currencyName: 'Australian Dollar',
    currencyCode: 'AUD',
    currencyNumber: '036',
    countryCodeIso: 'ISO 3166-2:CX',
    ccTLD: '.cx',
    phoneCode: '+6189164',
  },
  {
    name: 'Niue',
    nameOfficial: 'Niue',
    alpha2: 'NU',
    alpha3: 'NIU',
    countryCode: '570',
    currencyName: 'New Zealand Dollar',
    currencyCode: 'NZD',
    currencyNumber: '036',
    countryCodeIso: 'ISO 3166-2:NU',
    ccTLD: '.nu',
    phoneCode: '+683',
  },
  {
    name: 'India',
    nameOfficial: 'The Republic of India',
    alpha2: 'IN',
    alpha3: 'IND',
    countryCode: '356',
    currencyName: 'Indian Rupee',
    currencyCode: 'INR',
    currencyNumber: '360',
    countryCodeIso: 'ISO 3166-2:IN',
    ccTLD: '.in',
    phoneCode: '+91',
  },
  {
    name: 'Indonesia',
    nameOfficial: 'The Republic of Indonesia',
    alpha2: 'ID',
    alpha3: 'IDN',
    countryCode: '360',
    currencyName: 'Rupiah',
    currencyCode: 'IDR',
    currencyNumber: '364',
    countryCodeIso: 'ISO 3166-2:ID',
    ccTLD: '.id',
    phoneCode: '+62',
  },
  {
    name: 'Iran (Islamic Republic of)',
    nameOfficial: 'The Islamic Republic of Iran',
    alpha2: 'IR',
    alpha3: 'IRN',
    countryCode: '364',
    currencyName: 'Iranian Rial',
    currencyCode: 'IRR',
    currencyNumber: '368',
    countryCodeIso: 'ISO 3166-2:IR',
    ccTLD: '.ir',
    phoneCode: '+98',
  },
  {
    name: 'Ireland',
    nameOfficial: 'Ireland',
    alpha2: 'IE',
    alpha3: 'IRL',
    countryCode: '372',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '376',
    countryCodeIso: 'ISO 3166-2:IE',
    ccTLD: '.ie',
    phoneCode: '+353',
  },
  {
    name: 'Ivory Coast',
    nameOfficial: "The Republic of Côte d'Ivoire",
    alpha2: 'CI',
    alpha3: 'CIV',
    countryCode: '384',
    currencyName: 'CFA Franc BCEAO',
    currencyCode: 'XOF',
    currencyNumber: '388',
    countryCodeIso: 'ISO 3166-2:CI',
    ccTLD: '.ci',
    phoneCode: '+225',
  },
  {
    name: 'Jamaica',
    nameOfficial: 'Jamaica',
    alpha2: 'JM',
    alpha3: 'JAM',
    countryCode: '388',
    currencyName: 'Jamaican Dollar',
    currencyCode: 'JMD',
    currencyNumber: '392',
    countryCodeIso: 'ISO 3166-2:JM',
    ccTLD: '.jm',
    phoneCode: '+1876',
  },
  {
    name: 'Japan',
    nameOfficial: 'Japan',
    alpha2: 'JP',
    alpha3: 'JPN',
    countryCode: '392',
    currencyName: 'Yen',
    currencyCode: 'JPY',
    currencyNumber: '398',
    countryCodeIso: 'ISO 3166-2:JP',
    ccTLD: '.jp',
    phoneCode: '+81',
  },
  {
    name: 'Gambia',
    nameOfficial: 'The Republic of The Gambia',
    alpha2: 'GM',
    alpha3: 'GMB',
    countryCode: '270',
    currencyName: 'Dalasi',
    currencyCode: 'GMD',
    currencyNumber: '400',
    countryCodeIso: 'ISO 3166-2:GM',
    ccTLD: '.gm',
    phoneCode: '+220',
  },
  {
    name: 'Kazakhstan',
    nameOfficial: 'The Republic of Kazakhstan',
    alpha2: 'KZ',
    alpha3: 'KAZ',
    countryCode: '398',
    currencyName: 'Tenge',
    currencyCode: 'KZT',
    currencyNumber: '400',
    countryCodeIso: 'ISO 3166-2:KZ',
    ccTLD: '.kz',
    phoneCode: '+76,+77',
  },
  {
    name: 'Jordan',
    nameOfficial: 'The Hashemite Kingdom of Jordan',
    alpha2: 'JO',
    alpha3: 'JOR',
    countryCode: '400',
    currencyName: 'Jordanian Dinar',
    currencyCode: 'JOD',
    currencyNumber: '404',
    countryCodeIso: 'ISO 3166-2:JO',
    ccTLD: '.jo',
    phoneCode: '+962',
  },
  {
    name: 'Kenya',
    nameOfficial: 'The Republic of Kenya',
    alpha2: 'KE',
    alpha3: 'KEN',
    countryCode: '404',
    currencyName: 'Kenyan Shilling',
    currencyCode: 'KES',
    currencyNumber: '408',
    countryCodeIso: 'ISO 3166-2:KE',
    ccTLD: '.ke',
    phoneCode: '+254',
  },
  {
    name: "Korea (the Democratic People's Republic of) ",
    nameOfficial: "The Democratic People's Republic of Korea",
    alpha2: 'KP',
    alpha3: 'PRK',
    countryCode: '408',
    currencyName: 'North Korean Won',
    currencyCode: 'KPW',
    currencyNumber: '410',
    countryCodeIso: 'ISO 3166-2:KP',
    ccTLD: '.kp',
    phoneCode: '+850',
  },
  {
    name: 'Korea (the Republic of) ',
    nameOfficial: 'The Republic of Korea',
    alpha2: 'KR',
    alpha3: 'KOR',
    countryCode: '410',
    currencyName: 'Won',
    currencyCode: 'KRW',
    currencyNumber: '414',
    countryCodeIso: 'ISO 3166-2:KR',
    ccTLD: '.kr',
    phoneCode: '+82',
  },
  {
    name: 'Kuwait',
    nameOfficial: 'The State of Kuwait',
    alpha2: 'KW',
    alpha3: 'KWT',
    countryCode: '414',
    currencyName: 'Kuwaiti Dinar',
    currencyCode: 'KWD',
    currencyNumber: '417',
    countryCodeIso: 'ISO 3166-2:KW',
    ccTLD: '.kw',
    phoneCode: '+965',
  },
  {
    name: 'Kyrgyzstan',
    nameOfficial: 'The Kyrgyz Republic',
    alpha2: 'KG',
    alpha3: 'KGZ',
    countryCode: '417',
    currencyName: 'Som',
    currencyCode: 'KGS',
    currencyNumber: '418',
    countryCodeIso: 'ISO 3166-2:KG',
    ccTLD: '.kg',
    phoneCode: '+996',
  },
  {
    name: 'Laos',
    nameOfficial: "The Lao People's Democratic Republic",
    alpha2: 'LA',
    alpha3: 'LAO',
    countryCode: '418',
    currencyName: 'Kip',
    currencyCode: 'LAK',
    currencyNumber: '422',
    countryCodeIso: 'ISO 3166-2:LA',
    ccTLD: '.la',
    phoneCode: '+856',
  },
  {
    name: 'Lebanon',
    nameOfficial: 'The Lebanese Republic',
    alpha2: 'LB',
    alpha3: 'LBN',
    countryCode: '422',
    currencyName: 'Lebanese Pound',
    currencyCode: 'LBP',
    currencyNumber: '426',
    countryCodeIso: 'ISO 3166-2:LB',
    ccTLD: '.lb',
    phoneCode: '+961',
  },
  {
    name: 'Latvia',
    nameOfficial: 'The Republic of Latvia',
    alpha2: 'LV',
    alpha3: 'LVA',
    countryCode: '428',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '430',
    countryCodeIso: 'ISO 3166-2:LV',
    ccTLD: '.lv',
    phoneCode: '+371',
  },
  {
    name: 'Liberia',
    nameOfficial: 'The Republic of Liberia',
    alpha2: 'LR',
    alpha3: 'LBR',
    countryCode: '430',
    currencyName: 'Liberian Dollar',
    currencyCode: 'LRD',
    currencyNumber: '434',
    countryCodeIso: 'ISO 3166-2:LR',
    ccTLD: '.lr',
    phoneCode: '+231',
  },
  {
    name: 'Luxembourg',
    nameOfficial: 'The Grand Duchy of Luxembourg',
    alpha2: 'LU',
    alpha3: 'LUX',
    countryCode: '442',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '446',
    countryCodeIso: 'ISO 3166-2:LU',
    ccTLD: '.lu',
    phoneCode: '+352',
  },
  {
    name: 'Madagascar',
    nameOfficial: 'The Republic of Madagascar',
    alpha2: 'MG',
    alpha3: 'MDG',
    countryCode: '450',
    currencyName: 'Malagasy Ariary',
    currencyCode: 'MGA',
    currencyNumber: '454',
    countryCodeIso: 'ISO 3166-2:MG',
    ccTLD: '.mg',
    phoneCode: '+261',
  },
  {
    name: 'Malawi',
    nameOfficial: 'The Republic of Malawi',
    alpha2: 'MW',
    alpha3: 'MWI',
    countryCode: '454',
    currencyName: 'Kwacha',
    currencyCode: 'MWK',
    currencyNumber: '458',
    countryCodeIso: 'ISO 3166-2:MW',
    ccTLD: '.mw',
    phoneCode: '+265',
  },
  {
    name: 'Malaysia',
    nameOfficial: 'Malaysia',
    alpha2: 'MY',
    alpha3: 'MYS',
    countryCode: '458',
    currencyName: 'Malaysian Ringgit',
    currencyCode: 'MYR',
    currencyNumber: '462',
    countryCodeIso: 'ISO 3166-2:MY',
    ccTLD: '.my',
    phoneCode: '+60',
  },
  {
    name: 'Bahrain',
    nameOfficial: 'The Kingdom of Bahrain',
    alpha2: 'BH',
    alpha3: 'BHR',
    countryCode: '048',
    currencyName: 'Bahraini Dinar',
    currencyCode: 'BHD',
    currencyNumber: '048',
    countryCodeIso: 'ISO 3166-2:BH',
    ccTLD: '.bh',
    phoneCode: '+973',
  },
  {
    name: 'Mauritania',
    nameOfficial: 'The Islamic Republic of Mauritania',
    alpha2: 'MR',
    alpha3: 'MRT',
    countryCode: '478',
    currencyName: 'Ouguiya',
    currencyCode: 'MRU',
    currencyNumber: '480',
    countryCodeIso: 'ISO 3166-2:MR',
    ccTLD: '.mr',
    phoneCode: '+222',
  },
  {
    name: 'Mauritius',
    nameOfficial: 'The Republic of Mauritius',
    alpha2: 'MU',
    alpha3: 'MUS',
    countryCode: '480',
    currencyName: 'Mauritius Rupee',
    currencyCode: 'MUR',
    currencyNumber: '484',
    countryCodeIso: 'ISO 3166-2:MU',
    ccTLD: '.mu',
    phoneCode: '+230',
  },
  {
    name: 'Monaco',
    nameOfficial: 'The Principality of Monaco',
    alpha2: 'MC',
    alpha3: 'MCO',
    countryCode: '492',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '496',
    countryCodeIso: 'ISO 3166-2:MC',
    ccTLD: '.mc',
    phoneCode: '+377',
  },
  {
    name: 'Mongolia',
    nameOfficial: 'The State of Mongolia',
    alpha2: 'MN',
    alpha3: 'MNG',
    countryCode: '496',
    currencyName: 'Tugrik',
    currencyCode: 'MNT',
    currencyNumber: '498',
    countryCodeIso: 'ISO 3166-2:MN',
    ccTLD: '.mn',
    phoneCode: '+976',
  },
  {
    name: 'Bangladesh',
    nameOfficial: "The People's Republic of Bangladesh",
    alpha2: 'BD',
    alpha3: 'BGD',
    countryCode: '050',
    currencyName: 'Taka',
    currencyCode: 'BDT',
    currencyNumber: '050',
    countryCodeIso: 'ISO 3166-2:BD',
    ccTLD: '.bd',
    phoneCode: '+880',
  },
  {
    name: 'Montserrat',
    nameOfficial: 'Montserrat',
    alpha2: 'MS',
    alpha3: 'MSR',
    countryCode: '500',
    currencyName: 'East Caribbean Dollar',
    currencyCode: 'XCD',
    currencyNumber: '504',
    countryCodeIso: 'ISO 3166-2:MS',
    ccTLD: '.ms',
    phoneCode: '+1664',
  },
  {
    name: 'Sudan',
    nameOfficial: 'The Republic of the Sudan',
    alpha2: 'SD',
    alpha3: 'SDN',
    countryCode: '729',
    currencyName: 'Sudanese Pound',
    currencyCode: 'SDG',
    currencyNumber: '504',
    countryCodeIso: 'ISO 3166-2:SD',
    ccTLD: '.sd',
    phoneCode: '+249',
  },
  {
    name: 'Armenia',
    nameOfficial: 'The Republic of Armenia',
    alpha2: 'AM',
    alpha3: 'ARM',
    countryCode: '051',
    currencyName: 'Armenian Dram',
    currencyCode: 'AMD',
    currencyNumber: '051',
    countryCodeIso: 'ISO 3166-2:AM',
    ccTLD: '.am',
    phoneCode: '+374',
  },
  {
    name: 'Mozambique',
    nameOfficial: 'The Republic of Mozambique',
    alpha2: 'MZ',
    alpha3: 'MOZ',
    countryCode: '508',
    currencyName: 'Mozambique Metical',
    currencyCode: 'MZN',
    currencyNumber: '512',
    countryCodeIso: 'ISO 3166-2:MZ',
    ccTLD: '.mz',
    phoneCode: '+258',
  },
  {
    name: 'Oman',
    nameOfficial: 'The Sultanate of Oman',
    alpha2: 'OM',
    alpha3: 'OMN',
    countryCode: '512',
    currencyName: 'Rial Omani',
    currencyCode: 'OMR',
    currencyNumber: '516',
    countryCodeIso: 'ISO 3166-2:OM',
    ccTLD: '.om',
    phoneCode: '+968',
  },
  {
    name: 'Barbados',
    nameOfficial: 'Barbados',
    alpha2: 'BB',
    alpha3: 'BRB',
    countryCode: '052',
    currencyName: 'Barbados Dollar',
    currencyCode: 'BBD',
    currencyNumber: '052',
    countryCodeIso: 'ISO 3166-2:BB',
    ccTLD: '.bb',
    phoneCode: '+1246',
  },
  {
    name: 'Nauru',
    nameOfficial: 'The Republic of Nauru',
    alpha2: 'NR',
    alpha3: 'NRU',
    countryCode: '520',
    currencyName: 'Australian Dollar',
    currencyCode: 'AUD',
    currencyNumber: '524',
    countryCodeIso: 'ISO 3166-2:NR',
    ccTLD: '.nr',
    phoneCode: '+674',
  },
  {
    name: 'Aruba',
    nameOfficial: 'Aruba',
    alpha2: 'AW',
    alpha3: 'ABW',
    countryCode: '533',
    currencyName: 'Aruban Florin',
    currencyCode: 'AWG',
    currencyNumber: '532',
    countryCodeIso: 'ISO 3166-2:AW',
    ccTLD: '.aw',
    phoneCode: '+297',
  },
  {
    name: 'Netherlands',
    nameOfficial: 'The Kingdom of the Netherlands',
    alpha2: 'NL',
    alpha3: 'NLD',
    countryCode: '528',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '532',
    countryCodeIso: 'ISO 3166-2:NL',
    ccTLD: '.nl',
    phoneCode: '+31',
  },
  {
    name: 'Curaçao',
    nameOfficial: 'The Country of Curaçao',
    alpha2: 'CW',
    alpha3: 'CUW',
    countryCode: '531',
    currencyName: 'Netherlands Antillean guilder',
    currencyCode: 'ANG',
    currencyNumber: '533',
    countryCodeIso: 'ISO 3166-2:CW',
    ccTLD: '.cw',
    phoneCode: '+5999',
  },
  {
    name: 'New Caledonia',
    nameOfficial: 'New Caledonia',
    alpha2: 'NC',
    alpha3: 'NCL',
    countryCode: '540',
    currencyName: 'CFP Franc',
    currencyCode: 'XPF',
    currencyNumber: '548',
    countryCodeIso: 'ISO 3166-2:NC',
    ccTLD: '.nc',
    phoneCode: '+687',
  },
  {
    name: 'Nigeria',
    nameOfficial: 'The Federal Republic of Nigeria',
    alpha2: 'NG',
    alpha3: 'NGA',
    countryCode: '566',
    currencyName: 'Naira',
    currencyCode: 'NGN',
    currencyNumber: '554',
    countryCodeIso: 'ISO 3166-2:NG',
    ccTLD: '.ng',
    phoneCode: '+234',
  },
  {
    name: 'Philippines',
    nameOfficial: 'The Republic of the Philippines',
    alpha2: 'PH',
    alpha3: 'PHL',
    countryCode: '608',
    currencyName: 'Philippine Peso',
    currencyCode: 'PHP',
    currencyNumber: '554',
    countryCodeIso: 'ISO 3166-2:PH',
    ccTLD: '.ph',
    phoneCode: '+63',
  },
  {
    name: 'New Zealand',
    nameOfficial: 'New Zealand',
    alpha2: 'NZ',
    alpha3: 'NZL',
    countryCode: '554',
    currencyName: 'New Zealand Dollar',
    currencyCode: 'NZD',
    currencyNumber: '554',
    countryCodeIso: 'ISO 3166-2:NZ',
    ccTLD: '.nz',
    phoneCode: '+64',
  },
  {
    name: 'Vanuatu',
    nameOfficial: 'The Republic of Vanuatu',
    alpha2: 'VU',
    alpha3: 'VUT',
    countryCode: '548',
    currencyName: 'Vatu',
    currencyCode: 'VUV',
    currencyNumber: '554',
    countryCodeIso: 'ISO 3166-2:VU',
    ccTLD: '.vu',
    phoneCode: '+678',
  },
  {
    name: 'Tokelau',
    nameOfficial: 'Tokelau',
    alpha2: 'TK',
    alpha3: 'TKL',
    countryCode: '772',
    currencyName: 'New Zealand Dollar',
    currencyCode: 'NZD',
    currencyNumber: '554',
    countryCodeIso: 'ISO 3166-2:TK',
    ccTLD: '.tk',
    phoneCode: '+690',
  },
  {
    name: 'Cook Islands',
    nameOfficial: 'The Cook Islands',
    alpha2: 'CK',
    alpha3: 'COK',
    countryCode: '184',
    currencyName: 'New Zealand Dollar',
    currencyCode: 'NZD',
    currencyNumber: '558',
    countryCodeIso: 'ISO 3166-2:CK',
    ccTLD: '.ck',
    phoneCode: '+682',
  },
  {
    name: 'Niger',
    nameOfficial: 'The Republic of the Niger',
    alpha2: 'NE',
    alpha3: 'NER',
    countryCode: '562',
    currencyName: 'CFA Franc BCEAO',
    currencyCode: 'XOF',
    currencyNumber: '566',
    countryCodeIso: 'ISO 3166-2:NE',
    ccTLD: '.ne',
    phoneCode: '+227',
  },
  {
    name: 'Suriname',
    nameOfficial: 'The Republic of Suriname',
    alpha2: 'SR',
    alpha3: 'SUR',
    countryCode: '740',
    currencyName: 'Surinam Dollar',
    currencyCode: 'SRD',
    currencyNumber: '578',
    countryCodeIso: 'ISO 3166-2:SR',
    ccTLD: '.sr',
    phoneCode: '+597',
  },
  {
    name: 'Norfolk Island',
    nameOfficial: 'The Territory of Norfolk Island',
    alpha2: 'NF',
    alpha3: 'NFK',
    countryCode: '574',
    currencyName: 'Australian Dollar',
    currencyCode: 'AUD',
    currencyNumber: '578',
    countryCodeIso: 'ISO 3166-2:NF',
    ccTLD: '.nf',
    phoneCode: '+6723',
  },
  {
    name: 'Palau',
    nameOfficial: 'The Republic of Palau',
    alpha2: 'PW',
    alpha3: 'PLW',
    countryCode: '585',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '586',
    countryCodeIso: 'ISO 3166-2:PW',
    ccTLD: '.pw',
    phoneCode: '+680',
  },
  {
    name: 'Pakistan',
    nameOfficial: 'The Islamic Republic of Pakistan',
    alpha2: 'PK',
    alpha3: 'PAK',
    countryCode: '586',
    currencyName: 'Pakistan Rupee',
    currencyCode: 'PKR',
    currencyNumber: '590',
    countryCodeIso: 'ISO 3166-2:PK',
    ccTLD: '.pk',
    phoneCode: '+92',
  },
  {
    name: 'Panama',
    nameOfficial: 'The Republic of Panamá',
    alpha2: 'PA',
    alpha3: 'PAN',
    countryCode: '591',
    currencyName: 'Balboa',
    currencyCode: 'PAB',
    currencyNumber: '598',
    countryCodeIso: 'ISO 3166-2:PA',
    ccTLD: '.pa',
    phoneCode: '+507',
  },
  {
    name: 'Bermuda',
    nameOfficial: 'Bermuda',
    alpha2: 'BM',
    alpha3: 'BMU',
    countryCode: '060',
    currencyName: 'Bermudian Dollar',
    currencyCode: 'BMD',
    currencyNumber: '060',
    countryCodeIso: 'ISO 3166-2:BM',
    ccTLD: '.bm',
    phoneCode: '+1441',
  },
  {
    name: 'Papua New Guinea',
    nameOfficial: 'The Independent State of Papua New Guinea',
    alpha2: 'PG',
    alpha3: 'PNG',
    countryCode: '598',
    currencyName: 'Kina',
    currencyCode: 'PGK',
    currencyNumber: '600',
    countryCodeIso: 'ISO 3166-2:PG',
    ccTLD: '.pg',
    phoneCode: '+675',
  },
  {
    name: 'Paraguay',
    nameOfficial: 'The Republic of Paraguay',
    alpha2: 'PY',
    alpha3: 'PRY',
    countryCode: '600',
    currencyName: 'Guarani',
    currencyCode: 'PYG',
    currencyNumber: '604',
    countryCodeIso: 'ISO 3166-2:PY',
    ccTLD: '.py',
    phoneCode: '+595',
  },
  {
    name: 'Peru',
    nameOfficial: 'The Republic of Perú',
    alpha2: 'PE',
    alpha3: 'PER',
    countryCode: '604',
    currencyName: 'Nuevo Sol',
    currencyCode: 'PEN',
    currencyNumber: '608',
    countryCodeIso: 'ISO 3166-2:PE',
    ccTLD: '.pe',
    phoneCode: '+51',
  },
  {
    name: 'Puerto Rico',
    nameOfficial: 'The Commonwealth of Puerto Rico',
    alpha2: 'PR',
    alpha3: 'PRI',
    countryCode: '630',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '634',
    countryCodeIso: 'ISO 3166-2:PR',
    ccTLD: '.pr',
    phoneCode: '+1787,+1939',
  },
  {
    name: 'Bhutan',
    nameOfficial: 'The Kingdom of Bhutan',
    alpha2: 'BT',
    alpha3: 'BTN',
    countryCode: '064',
    currencyName: 'Ngultrum',
    currencyCode: 'BTN',
    currencyNumber: '064',
    countryCodeIso: 'ISO 3166-2:BT',
    ccTLD: '.bt',
    phoneCode: '+975',
  },
  {
    name: 'Romania',
    nameOfficial: 'Romania',
    alpha2: 'RO',
    alpha3: 'ROU',
    countryCode: '642',
    currencyName: 'Romanian Leu',
    currencyCode: 'RON',
    currencyNumber: '643',
    countryCodeIso: 'ISO 3166-2:RO',
    ccTLD: '.ro',
    phoneCode: '+40',
  },
  {
    name: 'Russian Federation ',
    nameOfficial: 'The Russian Federation',
    alpha2: 'RU',
    alpha3: 'RUS',
    countryCode: '643',
    currencyName: 'Russian Ruble',
    currencyCode: 'RUB',
    currencyNumber: '646',
    countryCodeIso: 'ISO 3166-2:RU',
    ccTLD: '.ru',
    phoneCode: '+7',
  },
  {
    name: 'Saint Barthélemy',
    nameOfficial: 'The Collectivity of Saint-Barthélemy',
    alpha2: 'BL',
    alpha3: 'BLM',
    countryCode: '652',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '654',
    countryCodeIso: 'ISO 3166-2:BL',
    ccTLD: '.bl',
    phoneCode: '+590',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    nameOfficial: 'The Plurinational State of Bolivia',
    alpha2: 'BO',
    alpha3: 'BOL',
    countryCode: '068',
    currencyName: 'Boliviano',
    currencyCode: 'BOB',
    currencyNumber: '068',
    countryCodeIso: 'ISO 3166-2:BO',
    ccTLD: '.bo',
    phoneCode: '+591',
  },
  {
    name: 'Sao Tome and Principe',
    nameOfficial: 'The Democratic Republic of São Tomé and Príncipe',
    alpha2: 'ST',
    alpha3: 'STP',
    countryCode: '678',
    currencyName: 'Dobra',
    currencyCode: 'STN',
    currencyNumber: '682',
    countryCodeIso: 'ISO 3166-2:ST',
    ccTLD: '.st',
    phoneCode: '+239',
  },
  {
    name: 'Serbia',
    nameOfficial: 'The Republic of Serbia',
    alpha2: 'RS',
    alpha3: 'SRB',
    countryCode: '688',
    currencyName: 'Serbian Dinar',
    currencyCode: 'RSD',
    currencyNumber: '690',
    countryCodeIso: 'ISO 3166-2:RS',
    ccTLD: '.rs',
    phoneCode: '+381',
  },
  {
    name: 'Seychelles',
    nameOfficial: 'The Republic of Seychelles',
    alpha2: 'SC',
    alpha3: 'SYC',
    countryCode: '690',
    currencyName: 'Seychelles Rupee',
    currencyCode: 'SCR',
    currencyNumber: '694',
    countryCodeIso: 'ISO 3166-2:SC',
    ccTLD: '.sc',
    phoneCode: '+248',
  },
  {
    name: 'Sierra Leone',
    nameOfficial: 'The Republic of Sierra Leone',
    alpha2: 'SL',
    alpha3: 'SLE',
    countryCode: '694',
    currencyName: 'Leone',
    currencyCode: 'SLL',
    currencyNumber: '702',
    countryCodeIso: 'ISO 3166-2:SL',
    ccTLD: '.sl',
    phoneCode: '+232',
  },
  {
    name: 'Slovakia',
    nameOfficial: 'The Slovak Republic',
    alpha2: 'SK',
    alpha3: 'SVK',
    countryCode: '703',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '704',
    countryCodeIso: 'ISO 3166-2:SK',
    ccTLD: '.sk',
    phoneCode: '+421',
  },
  {
    name: 'Slovenia',
    nameOfficial: 'The Republic of Slovenia',
    alpha2: 'SI',
    alpha3: 'SVN',
    countryCode: '705',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '706',
    countryCodeIso: 'ISO 3166-2:SI',
    ccTLD: '.si',
    phoneCode: '+386',
  },
  {
    name: 'Somalia',
    nameOfficial: 'The Federal Republic of Somalia',
    alpha2: 'SO',
    alpha3: 'SOM',
    countryCode: '706',
    currencyName: 'Somali Shilling',
    currencyCode: 'SOS',
    currencyNumber: '710',
    countryCodeIso: 'ISO 3166-2:SO',
    ccTLD: '.so',
    phoneCode: '+252',
  },
  {
    name: 'Botswana',
    nameOfficial: 'The Republic of Botswana',
    alpha2: 'BW',
    alpha3: 'BWA',
    countryCode: '072',
    currencyName: 'Pula',
    currencyCode: 'BWP',
    currencyNumber: '072',
    countryCodeIso: 'ISO 3166-2:BW',
    ccTLD: '.bw',
    phoneCode: '+267',
  },
  {
    name: 'Spain',
    nameOfficial: 'The Kingdom of Spain',
    alpha2: 'ES',
    alpha3: 'ESP',
    countryCode: '724',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '728',
    countryCodeIso: 'ISO 3166-2:ES',
    ccTLD: '.es',
    phoneCode: '+34',
  },
  {
    name: 'Svalbard and Jan Mayen',
    nameOfficial: 'Svalbard and Jan Mayen',
    alpha2: 'SJ',
    alpha3: 'SJM',
    countryCode: '744',
    currencyName: 'Norwegian Krone',
    currencyCode: 'NOK',
    currencyNumber: '748',
    countryCodeIso: 'ISO 3166-2:SJ',
    ccTLD: '',
    phoneCode: '+4779',
  },
  {
    name: 'Eswatini ',
    nameOfficial: 'The Kingdom of Eswatini',
    alpha2: 'SZ',
    alpha3: 'SWZ',
    countryCode: '748',
    currencyName: 'Lilangeni',
    currencyCode: 'SZL',
    currencyNumber: '752',
    countryCodeIso: 'ISO 3166-2:SZ',
    ccTLD: '.sz',
    phoneCode: '+268',
  },
  {
    name: 'Switzerland',
    nameOfficial: 'The Swiss Confederation',
    alpha2: 'CH',
    alpha3: 'CHE',
    countryCode: '756',
    currencyName: 'Swiss Franc',
    currencyCode: 'CHF',
    currencyNumber: '756',
    countryCodeIso: 'ISO 3166-2:CH',
    ccTLD: '.ch',
    phoneCode: '+41',
  },
  {
    name: 'Liechtenstein',
    nameOfficial: 'The Principality of Liechtenstein',
    alpha2: 'LI',
    alpha3: 'LIE',
    countryCode: '438',
    currencyName: 'Swiss Franc',
    currencyCode: 'CHF',
    currencyNumber: '756',
    countryCodeIso: 'ISO 3166-2:LI',
    ccTLD: '.li',
    phoneCode: '+423',
  },
  {
    name: 'Sweden',
    nameOfficial: 'The Kingdom of Sweden',
    alpha2: 'SE',
    alpha3: 'SWE',
    countryCode: '752',
    currencyName: 'Swedish Krona',
    currencyCode: 'SEK',
    currencyNumber: '756',
    countryCodeIso: 'ISO 3166-2:SE',
    ccTLD: '.se',
    phoneCode: '+46',
  },
  {
    name: 'Syria',
    nameOfficial: 'The Syrian Arab Republic',
    alpha2: 'SY',
    alpha3: 'SYR',
    countryCode: '760',
    currencyName: 'Syrian Pound',
    currencyCode: 'SYP',
    currencyNumber: '760',
    countryCodeIso: 'ISO 3166-2:SY',
    ccTLD: '.sy',
    phoneCode: '+963',
  },
  {
    name: 'Thailand',
    nameOfficial: 'The Kingdom of Thailand',
    alpha2: 'TH',
    alpha3: 'THA',
    countryCode: '764',
    currencyName: 'Baht',
    currencyCode: 'THB',
    currencyNumber: '764',
    countryCodeIso: 'ISO 3166-2:TH',
    ccTLD: '.th',
    phoneCode: '+66',
  },
  {
    name: 'Tonga',
    nameOfficial: 'The Kingdom of Tonga',
    alpha2: 'TO',
    alpha3: 'TON',
    countryCode: '776',
    currencyName: 'Pa’anga',
    currencyCode: 'TOP',
    currencyNumber: '776',
    countryCodeIso: 'ISO 3166-2:TO',
    ccTLD: '.to',
    phoneCode: '+676',
  },
  {
    name: 'Trinidad and Tobago',
    nameOfficial: 'The Republic of Trinidad and Tobago',
    alpha2: 'TT',
    alpha3: 'TTO',
    countryCode: '780',
    currencyName: 'Trinidad and Tobago Dollar',
    currencyCode: 'TTD',
    currencyNumber: '780',
    countryCodeIso: 'ISO 3166-2:TT',
    ccTLD: '.tt',
    phoneCode: '+1868',
  },
  {
    name: 'United Arab Emirates',
    nameOfficial: 'The United Arab Emirates',
    alpha2: 'AE',
    alpha3: 'ARE',
    countryCode: '784',
    currencyName: 'UAE Dirham',
    currencyCode: 'AED',
    currencyNumber: '784',
    countryCodeIso: 'ISO 3166-2:AE',
    ccTLD: '.ae',
    phoneCode: '+971',
  },
  {
    name: 'Tunisia',
    nameOfficial: 'The Republic of Tunisia',
    alpha2: 'TN',
    alpha3: 'TUN',
    countryCode: '788',
    currencyName: 'Tunisian Dinar',
    currencyCode: 'TND',
    currencyNumber: '788',
    countryCodeIso: 'ISO 3166-2:TN',
    ccTLD: '.tn',
    phoneCode: '+216',
  },
  {
    name: 'Uganda',
    nameOfficial: 'The Republic of Uganda',
    alpha2: 'UG',
    alpha3: 'UGA',
    countryCode: '800',
    currencyName: 'Uganda Shilling',
    currencyCode: 'UGX',
    currencyNumber: '800',
    countryCodeIso: 'ISO 3166-2:UG',
    ccTLD: '.ug',
    phoneCode: '+256',
  },
  {
    name: 'North Macedonia ',
    nameOfficial: 'Republic of North Macedonia',
    alpha2: 'MK',
    alpha3: 'MKD',
    countryCode: '807',
    currencyName: 'Denar',
    currencyCode: 'MKD',
    currencyNumber: '807',
    countryCodeIso: 'ISO 3166-2:MK',
    ccTLD: '.mk',
    phoneCode: '+389',
  },
  {
    name: 'Egypt',
    nameOfficial: 'The Arab Republic of Egypt',
    alpha2: 'EG',
    alpha3: 'EGY',
    countryCode: '818',
    currencyName: 'Egyptian Pound',
    currencyCode: 'EGP',
    currencyNumber: '818',
    countryCodeIso: 'ISO 3166-2:EG',
    ccTLD: '.eg',
    phoneCode: '+20',
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    nameOfficial: 'The United Kingdom of Great Britain and Northern Ireland',
    alpha2: 'GB',
    alpha3: 'GBR',
    countryCode: '826',
    currencyName: 'Pound Sterling',
    currencyCode: 'GBP',
    currencyNumber: '826',
    countryCodeIso: 'ISO 3166-2:GB',
    ccTLD: '.uk ',
    phoneCode: '+44',
  },
  {
    name: 'Tanzania, the United Republic of',
    nameOfficial: 'The United Republic of Tanzania',
    alpha2: 'TZ',
    alpha3: 'TZA',
    countryCode: '834',
    currencyName: 'Tanzanian Shilling',
    currencyCode: 'TZS',
    currencyNumber: '834',
    countryCodeIso: 'ISO 3166-2:TZ',
    ccTLD: '.tz',
    phoneCode: '+255',
  },
  {
    name: 'Belize',
    nameOfficial: 'Belize',
    alpha2: 'BZ',
    alpha3: 'BLZ',
    countryCode: '084',
    currencyName: 'Belize Dollar',
    currencyCode: 'BZD',
    currencyNumber: '084',
    countryCodeIso: 'ISO 3166-2:BZ',
    ccTLD: '.bz',
    phoneCode: '+501',
  },
  {
    name: 'United States of America',
    nameOfficial: 'The United States of America',
    alpha2: 'US',
    alpha3: 'USA',
    countryCode: '840',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:US',
    ccTLD: '.us',
    phoneCode: '+1',
  },
  {
    name: 'Virgin Islands (British) ',
    nameOfficial: 'The Virgin Islands',
    alpha2: 'VG',
    alpha3: 'VGB',
    countryCode: '092',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:VG',
    ccTLD: '.vg',
    phoneCode: '+1284',
  },
  {
    name: 'Virgin Islands (U.S.) ',
    nameOfficial: 'The Virgin Islands of the United States',
    alpha2: 'VI',
    alpha3: 'VIR',
    countryCode: '850',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:VI',
    ccTLD: '.vi',
    phoneCode: '+1340',
  },
  {
    name: 'Turks and Caicos Islands',
    nameOfficial: 'The Turks and Caicos Islands',
    alpha2: 'TC',
    alpha3: 'TCA',
    countryCode: '796',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:TC',
    ccTLD: '.tc',
    phoneCode: '+1649',
  },
  {
    name: 'Northern Mariana Islands',
    nameOfficial: 'The Commonwealth of the Northern Mariana Islands',
    alpha2: 'MP',
    alpha3: 'MNP',
    countryCode: '580',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:MP',
    ccTLD: '.mp',
    phoneCode: '+1670',
  },
  {
    name: 'American Samoa',
    nameOfficial: 'The Territory of American Samoa',
    alpha2: 'AS',
    alpha3: 'ASM',
    countryCode: '016',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:AS',
    ccTLD: '.as',
    phoneCode: '+1684',
  },
  {
    name: 'Sint Maarten (Netherlands)',
    nameOfficial: 'Sint Maarten',
    alpha2: 'SX',
    alpha3: 'SXM',
    countryCode: '534',
    currencyName: 'Netherlands Antillean guilder',
    currencyCode: 'ANG',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:SX',
    ccTLD: '.sx',
    phoneCode: '+1721',
  },
  {
    name: 'Dominican Republic',
    nameOfficial: 'The Dominican Republic',
    alpha2: 'DO',
    alpha3: 'DOM',
    countryCode: '214',
    currencyName: 'Dominican Peso',
    currencyCode: 'DOP',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:DO',
    ccTLD: '.do',
    phoneCode: '+1809,+1829,+1849',
  },
  {
    name: 'Guinea-Bissau',
    nameOfficial: 'The Republic of Guinea-Bissau',
    alpha2: 'GW',
    alpha3: 'GNB',
    countryCode: '624',
    currencyName: 'CFA Franc BCEAO',
    currencyCode: 'XOF',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:GW',
    ccTLD: '.gw',
    phoneCode: '+245',
  },
  {
    name: 'British Indian Ocean Territory',
    nameOfficial: 'The British Indian Ocean Territory',
    alpha2: 'IO',
    alpha3: 'IOT',
    countryCode: '086',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:IO',
    ccTLD: '.io',
    phoneCode: '+246',
  },
  {
    name: 'Norway',
    nameOfficial: 'The Kingdom of Norway',
    alpha2: 'NO',
    alpha3: 'NOR',
    countryCode: '578',
    currencyName: 'Norwegian Krone',
    currencyCode: 'NOK',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:NO',
    ccTLD: '.no',
    phoneCode: '+47',
  },
  {
    name: 'Guadeloupe',
    nameOfficial: 'Guadeloupe',
    alpha2: 'GP',
    alpha3: 'GLP',
    countryCode: '312',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:GP',
    ccTLD: '.gp',
    phoneCode: '+590',
  },
  {
    name: 'Timor-Leste ',
    nameOfficial: 'The Democratic Republic of Timor-Leste',
    alpha2: 'TL',
    alpha3: 'TLS',
    countryCode: '626',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:TL',
    ccTLD: '.tl',
    phoneCode: '+670',
  },
  {
    name: 'Micronesia (Federated States of)',
    nameOfficial: 'The Federated States of Micronesia',
    alpha2: 'FM',
    alpha3: 'FSM',
    countryCode: '583',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:FM',
    ccTLD: '.fm',
    phoneCode: '+691',
  },
  {
    name: 'Marshall Islands',
    nameOfficial: 'The Republic of the Marshall Islands',
    alpha2: 'MH',
    alpha3: 'MHL',
    countryCode: '584',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '840',
    countryCodeIso: 'ISO 3166-2:MH',
    ccTLD: '.mh',
    phoneCode: '+692',
  },
  {
    name: 'Uruguay',
    nameOfficial: 'The Oriental Republic of Uruguay',
    alpha2: 'UY',
    alpha3: 'URY',
    countryCode: '858',
    currencyName: 'Peso Uruguayo',
    currencyCode: 'UYU',
    currencyNumber: '858',
    countryCodeIso: 'ISO 3166-2:UY',
    ccTLD: '.uy',
    phoneCode: '+598',
  },
  {
    name: 'Uzbekistan',
    nameOfficial: 'The Republic of Uzbekistan',
    alpha2: 'UZ',
    alpha3: 'UZB',
    countryCode: '860',
    currencyName: 'Uzbekistan Sum',
    currencyCode: 'UZS',
    currencyNumber: '860',
    countryCodeIso: 'ISO 3166-2:UZ',
    ccTLD: '.uz',
    phoneCode: '+998',
  },
  {
    name: 'Samoa',
    nameOfficial: 'The Independent State of Samoa',
    alpha2: 'WS',
    alpha3: 'WSM',
    countryCode: '882',
    currencyName: 'Tala',
    currencyCode: 'WST',
    currencyNumber: '882',
    countryCodeIso: 'ISO 3166-2:WS',
    ccTLD: '.ws',
    phoneCode: '+685',
  },
  {
    name: 'Yemen',
    nameOfficial: 'The Republic of Yemen',
    alpha2: 'YE',
    alpha3: 'YEM',
    countryCode: '887',
    currencyName: 'Yemeni Rial',
    currencyCode: 'YER',
    currencyNumber: '886',
    countryCodeIso: 'ISO 3166-2:YE',
    ccTLD: '.ye',
    phoneCode: '+967',
  },
  {
    name: 'Zambia',
    nameOfficial: 'The Republic of Zambia',
    alpha2: 'ZM',
    alpha3: 'ZMB',
    countryCode: '894',
    currencyName: 'The Zambian Kwacha',
    currencyCode: 'ZMK',
    currencyNumber: '894',
    countryCodeIso: 'ISO 3166-2:ZM',
    ccTLD: '.zm',
    phoneCode: '+260',
  },
  {
    name: 'Solomon Islands',
    nameOfficial: 'The Solomon Islands',
    alpha2: 'SB',
    alpha3: 'SLB',
    countryCode: '090',
    currencyName: 'Solomon Islands Dollar',
    currencyCode: 'SBD',
    currencyNumber: '090',
    countryCodeIso: 'ISO 3166-2:SB',
    ccTLD: '.sb',
    phoneCode: '+677',
  },
  {
    name: 'Taiwan',
    nameOfficial: ' Taiwan (Province of China) ',
    alpha2: 'TW',
    alpha3: 'TWN',
    countryCode: '158',
    currencyName: 'New Taiwan Dollar',
    currencyCode: 'TWD',
    currencyNumber: '901',
    countryCodeIso: 'ISO 3166-2:TW',
    ccTLD: '.tw',
    phoneCode: '+886',
  },
  {
    name: 'Martinique',
    nameOfficial: 'Martinique',
    alpha2: 'MQ',
    alpha3: 'MTQ',
    countryCode: '474',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '929',
    countryCodeIso: 'ISO 3166-2:MQ',
    ccTLD: '.mq',
    phoneCode: '+596',
  },
  {
    name: 'San Marino',
    nameOfficial: 'The Republic of San Marino',
    alpha2: 'SM',
    alpha3: 'SMR',
    countryCode: '674',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '930',
    countryCodeIso: 'ISO 3166-2:SM',
    ccTLD: '.sm',
    phoneCode: '+378',
  },
  {
    name: 'Turkmenistan',
    nameOfficial: 'Turkmenistan',
    alpha2: 'TM',
    alpha3: 'TKM',
    countryCode: '795',
    currencyName: 'Turkmenistan New Manat',
    currencyCode: 'TMT',
    currencyNumber: '934',
    countryCodeIso: 'ISO 3166-2:TM',
    ccTLD: '.tm',
    phoneCode: '+993',
  },
  {
    name: 'Germany',
    nameOfficial: 'The Federal Republic of Germany',
    alpha2: 'DE',
    alpha3: 'DEU',
    countryCode: '276',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '936',
    countryCodeIso: 'ISO 3166-2:DE',
    ccTLD: '.de',
    phoneCode: '+49',
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    nameOfficial: 'The Bolivarian Republic of Venezuela',
    alpha2: 'VE',
    alpha3: 'VEN',
    countryCode: '862',
    currencyName: 'Venezuelan bolívar',
    currencyCode: 'VEF',
    currencyNumber: '937',
    countryCodeIso: 'ISO 3166-2:VE',
    ccTLD: '.ve',
    phoneCode: '+58',
  },
  {
    name: 'South Sudan',
    nameOfficial: 'The Republic of South Sudan',
    alpha2: 'SS',
    alpha3: 'SSD',
    countryCode: '728',
    currencyName: 'South Sudanese Pound',
    currencyCode: 'SSP',
    currencyNumber: '938',
    countryCodeIso: 'ISO 3166-2:SS',
    ccTLD: '.ss',
    phoneCode: '+211',
  },
  {
    name: 'Senegal',
    nameOfficial: 'The Republic of Senegal',
    alpha2: 'SN',
    alpha3: 'SEN',
    countryCode: '686',
    currencyName: 'CFA Franc BCEAO',
    currencyCode: 'XOF',
    currencyNumber: '941',
    countryCodeIso: 'ISO 3166-2:SN',
    ccTLD: '.sn',
    phoneCode: '+221',
  },
  {
    name: 'Morocco',
    nameOfficial: 'The Kingdom of Morocco',
    alpha2: 'MA',
    alpha3: 'MAR',
    countryCode: '504',
    currencyName: 'Moroccan Dirham',
    currencyCode: 'MAD',
    currencyNumber: '943',
    countryCodeIso: 'ISO 3166-2:MA',
    ccTLD: '.ma',
    phoneCode: '+212',
  },
  {
    name: 'Azerbaijan',
    nameOfficial: 'The Republic of Azerbaijan',
    alpha2: 'AZ',
    alpha3: 'AZE',
    countryCode: '031',
    currencyName: 'Azerbaijanian Manat',
    currencyCode: 'AZN',
    currencyNumber: '944',
    countryCodeIso: 'ISO 3166-2:AZ',
    ccTLD: '.az',
    phoneCode: '+994',
  },
  {
    name: 'Réunion',
    nameOfficial: 'Réunion',
    alpha2: 'RE',
    alpha3: 'REU',
    countryCode: '638',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '946',
    countryCodeIso: 'ISO 3166-2:RE',
    ccTLD: '.re',
    phoneCode: '+262',
  },
  {
    name: 'Turkey',
    nameOfficial: 'The Republic of Turkey',
    alpha2: 'TR',
    alpha3: 'TUR',
    countryCode: '792',
    currencyName: 'Turkish Lira',
    currencyCode: 'TRY',
    currencyNumber: '949',
    countryCodeIso: 'ISO 3166-2:TR',
    ccTLD: '.tr',
    phoneCode: '+90',
  },
  {
    name: 'Chad',
    nameOfficial: 'The Republic of Chad',
    alpha2: 'TD',
    alpha3: 'TCD',
    countryCode: '148',
    currencyName: 'CFA Franc BEAC',
    currencyCode: 'XAF',
    currencyNumber: '950',
    countryCodeIso: 'ISO 3166-2:TD',
    ccTLD: '.td',
    phoneCode: '+235',
  },
  {
    name: 'Central African Republic',
    nameOfficial: 'The Central African Republic',
    alpha2: 'CF',
    alpha3: 'CAF',
    countryCode: '140',
    currencyName: 'CFA Franc BEAC',
    currencyCode: 'XAF',
    currencyNumber: '950',
    countryCodeIso: 'ISO 3166-2:CF',
    ccTLD: '.cf',
    phoneCode: '+236',
  },
  {
    name: 'Cameroon',
    nameOfficial: 'The Republic of Cameroon',
    alpha2: 'CM',
    alpha3: 'CMR',
    countryCode: '120',
    currencyName: 'CFA Franc BEAC',
    currencyCode: 'XAF',
    currencyNumber: '950',
    countryCodeIso: 'ISO 3166-2:CM',
    ccTLD: '.cm',
    phoneCode: '+237',
  },
  {
    name: 'Congo ',
    nameOfficial: 'The Republic of the Congo',
    alpha2: 'CG',
    alpha3: 'COG',
    countryCode: '178',
    currencyName: 'CFA Franc BEAC',
    currencyCode: 'XAF',
    currencyNumber: '950',
    countryCodeIso: 'ISO 3166-2:CG',
    ccTLD: '.cg',
    phoneCode: '+242',
  },
  {
    name: 'Djibouti',
    nameOfficial: 'The Republic of Djibouti',
    alpha2: 'DJ',
    alpha3: 'DJI',
    countryCode: '262',
    currencyName: 'Djibouti Franc',
    currencyCode: 'DJF',
    currencyNumber: '950',
    countryCodeIso: 'ISO 3166-2:DJ',
    ccTLD: '.dj',
    phoneCode: '+253',
  },
  {
    name: 'El Salvador',
    nameOfficial: 'The Republic of El Salvador',
    alpha2: 'SV',
    alpha3: 'SLV',
    countryCode: '222',
    currencyName: 'El Salvador Colon',
    currencyCode: 'SVC',
    currencyNumber: '950',
    countryCodeIso: 'ISO 3166-2:SV',
    ccTLD: '.sv',
    phoneCode: '+503',
  },
  {
    name: 'Anguilla',
    nameOfficial: 'Anguilla',
    alpha2: 'AI',
    alpha3: 'AIA',
    countryCode: '660',
    currencyName: 'East Caribbean Dollar',
    currencyCode: 'XCD',
    currencyNumber: '951',
    countryCodeIso: 'ISO 3166-2:AI',
    ccTLD: '.ai',
    phoneCode: '+1264',
  },
  {
    name: 'Antigua and Barbuda',
    nameOfficial: 'Antigua and Barbuda',
    alpha2: 'AG',
    alpha3: 'ATG',
    countryCode: '028',
    currencyName: 'East Caribbean Dollar',
    currencyCode: 'XCD',
    currencyNumber: '951',
    countryCodeIso: 'ISO 3166-2:AG',
    ccTLD: '.ag',
    phoneCode: '+1268',
  },
  {
    name: 'Saint Kitts and Nevis',
    nameOfficial: 'Saint Kitts and Nevis',
    alpha2: 'KN',
    alpha3: 'KNA',
    countryCode: '659',
    currencyName: 'East Caribbean Dollar',
    currencyCode: 'XCD',
    currencyNumber: '951',
    countryCodeIso: 'ISO 3166-2:KN',
    ccTLD: '.kn',
    phoneCode: '+1869',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    nameOfficial: 'Saint Helena, Ascension and Tristan da Cunha',
    alpha2: 'SH',
    alpha3: 'SHN',
    countryCode: '654',
    currencyName: 'Saint Helena Pound',
    currencyCode: 'SHP',
    currencyNumber: '951',
    countryCodeIso: 'ISO 3166-2:SH',
    ccTLD: '.sh',
    phoneCode: '+290',
  },
  {
    name: 'Greenland',
    nameOfficial: 'Kalaallit Nunaat',
    alpha2: 'GL',
    alpha3: 'GRL',
    countryCode: '304',
    currencyName: 'Danish Krone',
    currencyCode: 'DKK',
    currencyNumber: '951',
    countryCodeIso: 'ISO 3166-2:GL',
    ccTLD: '.gl',
    phoneCode: '+299',
  },
  {
    name: 'Montenegro',
    nameOfficial: 'Montenegro',
    alpha2: 'ME',
    alpha3: 'MNE',
    countryCode: '499',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '951',
    countryCodeIso: 'ISO 3166-2:ME',
    ccTLD: '.me',
    phoneCode: '+382',
  },
  {
    name: 'Denmark',
    nameOfficial: 'The Kingdom of Denmark',
    alpha2: 'DK',
    alpha3: 'DNK',
    countryCode: '208',
    currencyName: 'Danish Krone',
    currencyCode: 'DKK',
    currencyNumber: '951',
    countryCodeIso: 'ISO 3166-2:DK',
    ccTLD: '.dk',
    phoneCode: '+45',
  },
  {
    name: 'Saint Pierre and Miquelon',
    nameOfficial: 'The Overseas Collectivity of Saint-Pierre and Miquelon',
    alpha2: 'PM',
    alpha3: 'SPM',
    countryCode: '666',
    currencyName: 'Euro		',
    currencyCode: 'EUR',
    currencyNumber: '951',
    countryCodeIso: 'ISO 3166-2:PM',
    ccTLD: '.pm',
    phoneCode: '+508',
  },
  {
    name: 'Burkina Faso',
    nameOfficial: 'Burkina Faso',
    alpha2: 'BF',
    alpha3: 'BFA',
    countryCode: '854',
    currencyName: 'CFA Franc BCEAO',
    currencyCode: 'XOF',
    currencyNumber: '952',
    countryCodeIso: 'ISO 3166-2:BF',
    ccTLD: '.bf',
    phoneCode: '+226',
  },
  {
    name: 'Togo',
    nameOfficial: 'The Togolese Republic',
    alpha2: 'TG',
    alpha3: 'TGO',
    countryCode: '768',
    currencyName: 'CFA Franc BCEAO',
    currencyCode: 'XOF',
    currencyNumber: '952',
    countryCodeIso: 'ISO 3166-2:TG',
    ccTLD: '.tg',
    phoneCode: '+228',
  },
  {
    name: 'Portugal',
    nameOfficial: 'The Portuguese Republic',
    alpha2: 'PT',
    alpha3: 'PRT',
    countryCode: '620',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '952',
    countryCodeIso: 'ISO 3166-2:PT',
    ccTLD: '.pt',
    phoneCode: '+351',
  },
  {
    name: 'Italy',
    nameOfficial: 'The Italian Republic',
    alpha2: 'IT',
    alpha3: 'ITA',
    countryCode: '380',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '952',
    countryCodeIso: 'ISO 3166-2:IT',
    ccTLD: '.it',
    phoneCode: '+39',
  },
  {
    name: 'Czech Republic',
    nameOfficial: 'The Czech Republic',
    alpha2: 'CZ',
    alpha3: 'CZE',
    countryCode: '203',
    currencyName: 'Czech Koruna',
    currencyCode: 'CZK',
    currencyNumber: '952',
    countryCodeIso: 'ISO 3166-2:CZ',
    ccTLD: '.cz',
    phoneCode: '+420',
  },
  {
    name: 'Nicaragua',
    nameOfficial: 'The Republic of Nicaragua',
    alpha2: 'NI',
    alpha3: 'NIC',
    countryCode: '558',
    currencyName: 'Cordoba Oro',
    currencyCode: 'NIO',
    currencyNumber: '952',
    countryCodeIso: 'ISO 3166-2:NI',
    ccTLD: '.ni',
    phoneCode: '+505',
  },
  {
    name: 'Maldives',
    nameOfficial: 'The Republic of Maldives',
    alpha2: 'MV',
    alpha3: 'MDV',
    countryCode: '462',
    currencyName: 'Rufiyaa',
    currencyCode: 'MVR',
    currencyNumber: '952',
    countryCodeIso: 'ISO 3166-2:MV',
    ccTLD: '.mv',
    phoneCode: '+960',
  },
  {
    name: 'Saudi Arabia',
    nameOfficial: 'The Kingdom of Saudi Arabia',
    alpha2: 'SA',
    alpha3: 'SAU',
    countryCode: '682',
    currencyName: 'Saudi Riyal',
    currencyCode: 'SAR',
    currencyNumber: '952',
    countryCodeIso: 'ISO 3166-2:SA',
    ccTLD: '.sa',
    phoneCode: '+966',
  },
  {
    name: 'French Guiana',
    nameOfficial: 'Guyane',
    alpha2: 'GF',
    alpha3: 'GUF',
    countryCode: '254',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '953',
    countryCodeIso: 'ISO 3166-2:GF',
    ccTLD: '.gf',
    phoneCode: '+594',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    nameOfficial: 'Bonaire, Sint Eustatius and Saba',
    alpha2: 'BQ',
    alpha3: 'BES',
    countryCode: '535',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencyNumber: '953',
    countryCodeIso: 'ISO 3166-2:BQ',
    ccTLD: '.nl ',
    phoneCode: '+5997',
  },
  {
    name: 'Wallis and Futuna',
    nameOfficial: 'The Territory of the Wallis and Futuna Islands',
    alpha2: 'WF',
    alpha3: 'WLF',
    countryCode: '876',
    currencyName: 'The CFP franc',
    currencyCode: 'XPF',
    currencyNumber: '953',
    countryCodeIso: 'ISO 3166-2:WF',
    ccTLD: '.wf',
    phoneCode: '+681',
  },
  {
    name: 'Brunei Darussalam ',
    nameOfficial: 'The Nation of Brunei, the Abode of Peace',
    alpha2: 'BN',
    alpha3: 'BRN',
    countryCode: '096',
    currencyName: 'Brunei Dollar',
    currencyCode: 'BND',
    currencyNumber: '096',
    countryCodeIso: 'ISO 3166-2:BN',
    ccTLD: '.bn',
    phoneCode: '+673',
  },
  {
    name: 'Western Sahara ',
    nameOfficial: 'The Sahrawi Arab Democratic Republic',
    alpha2: 'EH',
    alpha3: 'ESH',
    countryCode: '732',
    currencyName: 'Moroccan Dirham',
    currencyCode: 'MAD',
    currencyNumber: '968',
    countryCodeIso: 'ISO 3166-2:EH',
    ccTLD: '.eh',
    phoneCode: '+212',
  },
  {
    name: 'Macao ',
    nameOfficial: 'Macao Special Administrative Region of China',
    alpha2: 'MO',
    alpha3: 'MAC',
    countryCode: '446',
    currencyName: 'Pataca',
    currencyCode: 'MOP',
    currencyNumber: '969',
    countryCodeIso: 'ISO 3166-2:MO',
    ccTLD: '.mo',
    phoneCode: '+853',
  },
  {
    name: 'Afghanistan',
    nameOfficial: 'The Islamic Republic of Afghanistan',
    alpha2: 'AF',
    alpha3: 'AFG',
    countryCode: '004',
    currencyName: 'Afghani',
    currencyCode: 'AFN',
    currencyNumber: '971',
    countryCodeIso: 'ISO 3166-2:AF',
    ccTLD: '.af',
    phoneCode: '+93',
  },
  {
    name: 'Tajikistan',
    nameOfficial: 'The Republic of Tajikistan',
    alpha2: 'TJ',
    alpha3: 'TJK',
    countryCode: '762',
    currencyName: 'Somoni',
    currencyCode: 'TJS',
    currencyNumber: '972',
    countryCodeIso: 'ISO 3166-2:TJ',
    ccTLD: '.tj',
    phoneCode: '+992',
  },
  {
    name: 'Angola',
    nameOfficial: 'The Republic of Angola',
    alpha2: 'AO',
    alpha3: 'AGO',
    countryCode: '024',
    currencyName: 'Kwanza',
    currencyCode: 'AOA',
    currencyNumber: '973',
    countryCodeIso: 'ISO 3166-2:AO',
    ccTLD: '.ao',
    phoneCode: '+244',
  },
  {
    name: 'Belarus',
    nameOfficial: 'The Republic of Belarus',
    alpha2: 'BY',
    alpha3: 'BLR',
    countryCode: '112',
    currencyName: 'Belarussian Ruble',
    currencyCode: 'BYR',
    currencyNumber: '974',
    countryCodeIso: 'ISO 3166-2:BY',
    ccTLD: '.by',
    phoneCode: '+375',
  },
  {
    name: 'Bulgaria',
    nameOfficial: 'The Republic of Bulgaria',
    alpha2: 'BG',
    alpha3: 'BGR',
    countryCode: '100',
    currencyName: 'Bulgarian Lev',
    currencyCode: 'BGN',
    currencyNumber: '975',
    countryCodeIso: 'ISO 3166-2:BG',
    ccTLD: '.bg',
    phoneCode: '+359',
  },
  {
    name: 'Congo (the Democratic Republic of the)',
    nameOfficial: 'The Democratic Republic of the Congo',
    alpha2: 'CD',
    alpha3: 'COD',
    countryCode: '180',
    currencyName: 'Congolese Franc',
    currencyCode: 'CDF',
    currencyNumber: '976',
    countryCodeIso: 'ISO 3166-2:CD',
    ccTLD: '.cd',
    phoneCode: '+243',
  },
  {
    name: 'Bosnia and Herzegovina',
    nameOfficial: 'Bosnia and Herzegovina',
    alpha2: 'BA',
    alpha3: 'BIH',
    countryCode: '070',
    currencyName: 'Convertible Mark',
    currencyCode: 'BAM',
    currencyNumber: '977',
    countryCodeIso: 'ISO 3166-2:BA',
    ccTLD: '.ba',
    phoneCode: '+387',
  },
  {
    name: 'Grenada',
    nameOfficial: 'Grenada',
    alpha2: 'GD',
    alpha3: 'GRD',
    countryCode: '308',
    currencyName: 'East Caribbean Dollar',
    currencyCode: 'XCD',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:GD',
    ccTLD: '.gd',
    phoneCode: '+1473',
  },
  {
    name: 'Saint Lucia',
    nameOfficial: 'Saint Lucia',
    alpha2: 'LC',
    alpha3: 'LCA',
    countryCode: '662',
    currencyName: 'East Caribbean Dollar',
    currencyCode: 'XCD',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:LC',
    ccTLD: '.lc',
    phoneCode: '+1758',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    nameOfficial: 'Saint Vincent and the Grenadines',
    alpha2: 'VC',
    alpha3: 'VCT',
    countryCode: '670',
    currencyName: 'East Caribbean Dollar',
    currencyCode: 'XCD',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:VC',
    ccTLD: '.vc',
    phoneCode: '+1784',
  },
  {
    name: 'Libya',
    nameOfficial: 'The State of Libya',
    alpha2: 'LY',
    alpha3: 'LBY',
    countryCode: '434',
    currencyName: 'Libyan Dinar',
    currencyCode: 'LYD',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:LY',
    ccTLD: '.ly',
    phoneCode: '+218',
  },
  {
    name: 'Mali',
    nameOfficial: 'The Republic of Mali',
    alpha2: 'ML',
    alpha3: 'MLI',
    countryCode: '466',
    currencyName: 'CFA Franc BCEAO',
    currencyCode: 'XOF',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:ML',
    ccTLD: '.ml',
    phoneCode: '+223',
  },
  {
    name: 'Rwanda',
    nameOfficial: 'The Republic of Rwanda',
    alpha2: 'RW',
    alpha3: 'RWA',
    countryCode: '646',
    currencyName: 'Rwanda Franc',
    currencyCode: 'RWF',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:RW',
    ccTLD: '.rw',
    phoneCode: '+250',
  },
  {
    name: 'Zimbabwe',
    nameOfficial: 'The Republic of Zimbabwe',
    alpha2: 'ZW',
    alpha3: 'ZWE',
    countryCode: '716',
    currencyName: 'The Zimbabwean dollar',
    currencyCode: 'ZWL',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:ZW',
    ccTLD: '.zw',
    phoneCode: '+25524',
  },
  {
    name: 'Mayotte',
    nameOfficial: 'The Department of Mayotte',
    alpha2: 'YT',
    alpha3: 'MYT',
    countryCode: '175',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:YT',
    ccTLD: '.yt',
    phoneCode: '+262',
  },
  {
    name: 'Lesotho',
    nameOfficial: 'The Kingdom of Lesotho',
    alpha2: 'LS',
    alpha3: 'LSO',
    countryCode: '426',
    currencyName: 'Loti',
    currencyCode: 'LSL',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:LS',
    ccTLD: '.ls',
    phoneCode: '+266',
  },
  {
    name: 'Eritrea',
    nameOfficial: 'The State of Eritrea',
    alpha2: 'ER',
    alpha3: 'ERI',
    countryCode: '232',
    currencyName: 'Nakfa',
    currencyCode: 'ERN',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:ER',
    ccTLD: '.er',
    phoneCode: '+291',
  },
  {
    name: 'Belgium',
    nameOfficial: 'The Kingdom of Belgium',
    alpha2: 'BE',
    alpha3: 'BEL',
    countryCode: '056',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:BE',
    ccTLD: '.be',
    phoneCode: '+32',
  },
  {
    name: 'France ',
    nameOfficial: 'The French Republic',
    alpha2: 'FR',
    alpha3: 'FRA',
    countryCode: '250',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:FR',
    ccTLD: '.fr',
    phoneCode: '+33',
  },
  {
    name: 'Malta',
    nameOfficial: 'The Republic of Malta',
    alpha2: 'MT',
    alpha3: 'MLT',
    countryCode: '470',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:MT',
    ccTLD: '.mt',
    phoneCode: '+356',
  },
  {
    name: 'Finland',
    nameOfficial: 'The Republic of Finland',
    alpha2: 'FI',
    alpha3: 'FIN',
    countryCode: '246',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:FI',
    ccTLD: '.fi',
    phoneCode: '+358',
  },
  {
    name: 'Åland Islands',
    nameOfficial: 'Åland',
    alpha2: 'AX',
    alpha3: 'ALA',
    countryCode: '248',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:AX',
    ccTLD: '.ax',
    phoneCode: '+35818',
  },
  {
    name: 'Lithuania',
    nameOfficial: 'The Republic of Lithuania',
    alpha2: 'LT',
    alpha3: 'LTU',
    countryCode: '440',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:LT',
    ccTLD: '.lt',
    phoneCode: '+370',
  },
  {
    name: 'Moldova (the Republic of)',
    nameOfficial: 'The Republic of Moldova',
    alpha2: 'MD',
    alpha3: 'MDA',
    countryCode: '498',
    currencyName: 'Moldovan Leu',
    currencyCode: 'MDL',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:MD',
    ccTLD: '.md',
    phoneCode: '+373',
  },
  {
    name: 'Andorra',
    nameOfficial: 'The Principality of Andorra',
    alpha2: 'AD',
    alpha3: 'AND',
    countryCode: '020',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:AD',
    ccTLD: '.ad',
    phoneCode: '+376',
  },
  {
    name: 'Austria',
    nameOfficial: 'The Republic of Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    countryCode: '040',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:AT',
    ccTLD: '.at',
    phoneCode: '+43',
  },
  {
    name: 'Poland',
    nameOfficial: 'The Republic of Poland',
    alpha2: 'PL',
    alpha3: 'POL',
    countryCode: '616',
    currencyName: 'Zloty',
    currencyCode: 'PLN',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:PL',
    ccTLD: '.pl',
    phoneCode: '+48',
  },
  {
    name: 'Mexico',
    nameOfficial: 'The United Mexican States',
    alpha2: 'MX',
    alpha3: 'MEX',
    countryCode: '484',
    currencyName: 'Mexican Peso',
    currencyCode: 'MXN',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:MX',
    ccTLD: '.mx',
    phoneCode: '+52',
  },
  {
    name: 'Cuba',
    nameOfficial: 'The Republic of Cuba',
    alpha2: 'CU',
    alpha3: 'CUB',
    countryCode: '192',
    currencyName: 'Cuban Peso',
    currencyCode: 'CUP',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:CU',
    ccTLD: '.cu',
    phoneCode: '+53',
  },
  {
    name: 'Saint Martin (France)',
    nameOfficial: 'The Collectivity of Saint-Martin',
    alpha2: 'MF',
    alpha3: 'MAF',
    countryCode: '663',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:MF',
    ccTLD: '.mf',
    phoneCode: '+590',
  },
  {
    name: 'Singapore',
    nameOfficial: 'The Republic of Singapore',
    alpha2: 'SG',
    alpha3: 'SGP',
    countryCode: '702',
    currencyName: 'Singapore Dollar',
    currencyCode: 'SGD',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:SG',
    ccTLD: '.sg',
    phoneCode: '+65',
  },
  {
    name: 'Fiji',
    nameOfficial: 'The Republic of Fiji',
    alpha2: 'FJ',
    alpha3: 'FJI',
    countryCode: '242',
    currencyName: 'Fiji Dollar',
    currencyCode: 'FJD',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:FJ',
    ccTLD: '.fj',
    phoneCode: '+679',
  },
  {
    name: 'Kiribati',
    nameOfficial: 'The Republic of Kiribati',
    alpha2: 'KI',
    alpha3: 'KIR',
    countryCode: '296',
    currencyName: 'Australian Dollar',
    currencyCode: 'AUD',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:KI',
    ccTLD: '.ki',
    phoneCode: '+686',
  },
  {
    name: 'Viet Nam ',
    nameOfficial: 'The Socialist Republic of Viet Nam',
    alpha2: 'VN',
    alpha3: 'VNM',
    countryCode: '704',
    currencyName: 'Dong',
    currencyCode: 'VND',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:VN',
    ccTLD: '.vn',
    phoneCode: '+84',
  },
  {
    name: 'Iraq',
    nameOfficial: 'The Republic of Iraq',
    alpha2: 'IQ',
    alpha3: 'IRQ',
    countryCode: '368',
    currencyName: 'Iraqi Dinar',
    currencyCode: 'IQD',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:IQ',
    ccTLD: '.iq',
    phoneCode: '+964',
  },
  {
    name: 'Palestine, State of',
    nameOfficial: 'The State of Palestine',
    alpha2: 'PS',
    alpha3: 'PSE',
    countryCode: '275',
    currencyName: 'Jordanian dinar',
    currencyCode: 'JOD',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:PS',
    ccTLD: '.ps',
    phoneCode: '+970',
  },
  {
    name: 'Israel',
    nameOfficial: 'The State of Israel',
    alpha2: 'IL',
    alpha3: 'ISR',
    countryCode: '376',
    currencyName: 'New Israeli Sheqel',
    currencyCode: 'ILS',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:IL',
    ccTLD: '.il',
    phoneCode: '+972',
  },
  {
    name: 'Qatar',
    nameOfficial: 'The State of Qatar',
    alpha2: 'QA',
    alpha3: 'QAT',
    countryCode: '634',
    currencyName: 'Qatari Rial',
    currencyCode: 'QAR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:QA',
    ccTLD: '.qa',
    phoneCode: '+974',
  },
  {
    name: 'Nepal',
    nameOfficial: 'The Federal Democratic Republic of Nepal',
    alpha2: 'NP',
    alpha3: 'NPL',
    countryCode: '524',
    currencyName: 'Nepalese Rupee',
    currencyCode: 'NPR',
    currencyNumber: '978',
    countryCodeIso: 'ISO 3166-2:NP',
    ccTLD: '.np',
    phoneCode: '+977',
  },
  {
    name: 'Ukraine',
    nameOfficial: 'Ukraine',
    alpha2: 'UA',
    alpha3: 'UKR',
    countryCode: '804',
    currencyName: 'Hryvnia',
    currencyCode: 'UAH',
    currencyNumber: '980',
    countryCodeIso: 'ISO 3166-2:UA',
    ccTLD: '.ua',
    phoneCode: '+380',
  },
  {
    name: 'Gabon',
    nameOfficial: 'The Gabonese Republic',
    alpha2: 'GA',
    alpha3: 'GAB',
    countryCode: '266',
    currencyName: 'CFA Franc BEAC',
    currencyCode: 'XAF',
    currencyNumber: '981',
    countryCodeIso: 'ISO 3166-2:GA',
    ccTLD: '.ga',
    phoneCode: '+241',
  },
  {
    name: 'Pitcairn Islands',
    nameOfficial: 'The Pitcairn, Henderson, Ducie and Oeno Islands',
    alpha2: 'PN',
    alpha3: 'PCN',
    countryCode: '612',
    currencyName: 'New Zealand Dollar',
    currencyCode: 'NZD',
    currencyNumber: '985',
    countryCodeIso: 'ISO 3166-2:PN',
    ccTLD: '.pn',
    phoneCode: '+64',
  },
  {
    name: 'Brazil',
    nameOfficial: 'The Federative Republic of Brazil',
    alpha2: 'BR',
    alpha3: 'BRA',
    countryCode: '076',
    currencyName: 'Brazilian Real',
    currencyCode: 'BRL',
    currencyNumber: '986',
    countryCodeIso: 'ISO 3166-2:BR',
    ccTLD: '.br',
    phoneCode: '+55',
  },
  {
    name: 'South Africa',
    nameOfficial: 'The Republic of South Africa',
    alpha2: 'ZA',
    alpha3: 'ZAF',
    countryCode: '710',
    currencyName: 'Rand',
    currencyCode: 'ZAR',
    currencyNumber: '',
    countryCodeIso: 'ISO 3166-2:ZA',
    ccTLD: '.za',
    phoneCode: '+27',
  },
  {
    name: 'Jersey',
    nameOfficial: 'The Bailiwick of Jersey',
    alpha2: 'JE',
    alpha3: 'JEY',
    countryCode: '832',
    currencyName: 'The Jersey pound',
    currencyCode: 'JEP',
    currencyNumber: '',
    countryCodeIso: 'ISO 3166-2:JE',
    ccTLD: '.je',
    phoneCode: '+441534',
  },
  {
    name: 'Guernsey',
    nameOfficial: 'The Bailiwick of Guernsey',
    alpha2: 'GG',
    alpha3: 'GGY',
    countryCode: '831',
    currencyName: 'The Guernsey pound',
    currencyCode: 'GGP',
    currencyNumber: '',
    countryCodeIso: 'ISO 3166-2:GG',
    ccTLD: '.gg',
    phoneCode: '+447',
  },
  {
    name: 'Isle of Man',
    nameOfficial: 'The Isle of Man',
    alpha2: 'IM',
    alpha3: 'IMN',
    countryCode: '833',
    currencyName: 'The Isle of Man Pound',
    currencyCode: 'IMP',
    currencyNumber: '',
    countryCodeIso: 'ISO 3166-2:IM',
    ccTLD: '.im',
    phoneCode: '+447',
  },
  {
    name: 'Tuvalu',
    nameOfficial: 'Tuvalu',
    alpha2: 'TV',
    alpha3: 'TUV',
    countryCode: '798',
    currencyName: 'Tuvaluan dollar',
    currencyCode: 'TVD',
    currencyNumber: '',
    countryCodeIso: 'ISO 3166-2:TV',
    ccTLD: '.tv',
    phoneCode: '+688',
  },
];
